name: Commit Message Lint

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Lint commit messages
        run: |
          git fetch origin main
          COMMITS=$(git log origin/main..HEAD --pretty=format:"%H")
          echo "$COMMITS" | while read commit; do
            npx commitlint --from=$commit --to=$commit --verbose
          done
