name: Lint Commit Messages

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main, test]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v6
